project:
  type: book
  output-dir: docs

book:
  title: "Evaluating the Performance of Machine Learning Models in Remote Sensing for Sustainable Development Goals: A Meta-Analysis"
  author: 
  - name: "Nina Maria Leach"
    affiliations:
        - name: "UNIVERSITEIT LEIDEN"
          department: "STATISTICS AND DATA SCIENCE"
  sidebar: 
    background: "#F5F5F5"
    logo: images/ul.logo.png
    search: true
  date: 2025-07-07
  date-format: long
 
  chapters:
    - frontmatter/abstract.qmd
    - index.qmd
    - chapters/intro.qmd
    - chapters/background.qmd
    - chapters/methods.qmd
    - chapters/results.qmd
    - chapters/discussion.qmd
    - frontmatter/acknowledgement.qmd
    - references.qmd
  appendices:
    - appendix/app1-paper_selection/app1-paper_selection.qmd
    - appendix/app2-data.qmd

  
  search:
    location: navbar
    type: overlay
  output-file: NMLeach_MasterThesis
  downloads:
    -  pdf


# table of content and depth of numbering set at chapter level  
toc: true
number-depth: 1

execute:
  warning: false
  massage: false

bibliography: references.bib
csl: apa7.csl

format-links: true

format:
  html:
    theme: cosmo
    code-fold: true
    html-table-processing: none
    include-in-header: in-line_math_mode.html
  pdf:
    include-in-header: 
      text: |
        \usepackage{booktabs}
        \usepackage{textcomp}
        \usepackage{graphicx}
        \usepackage{setspace}
        \usepackage{longtable}
        \usepackage{lscape}
        \newcommand{\blandscape}{\begin{landscape}}
        \newcommand{\elandscape}{\end{landscape}}
        \usepackage{float}
        \floatplacement{table}{H}
        \pagenumbering{gobble}
        \usepackage{titlesec}
        \titleformat{\chapter}[display]
        {\normalfont\huge\bfseries}{}{0pt}{\Huge}
        \titlespacing*{\chapter}{0pt}{-20pt}{10pt} % to adjust header spacing
      
        
    fig-pos: 'H'
    template-partials:
      - frontmatter/before-body.tex
    documentclass: report
    classoption: ["open=any"]
    latex_engine: xelatex
    extra_dependencies: ["setspace", "geometry"]
    latex-max-runs: 3
   
    keep-tex: false
    link-citations: true
    colorlinks: false
    papersize: a4
    fontsize: 11pt
    
    linestretch: 1.5
    geometry:
      - inner=1.9cm
      - outer=1.9cm
      - top=1.8cm
      - bottom=2cm
      - headsep=9pt
      - headheight=9pt
      - footskip=33pt
      - ignorehead
      - ignorefoot
      - heightrounded
    



editor: visual

