project:
  type: book
  output-dir: docs

book:
  title: "Evaluating the Performance of Machine Learning Models in Remote Sensing for Sustainable Development Goals: A Meta-Analysis"
  author: 
  - name: "Nina Maria Leach"
    affiliations:
        - name: "UNIVERSITEIT LEIDEN"
          department: "STATISTICS AND DATA SCIENCE"
  sidebar: 
    background: "#F5F5F5"
    logo: images/ul.logo.png
    search: true
  date: " 01-11-2024"
 
  chapters:
    - index.qmd
    #- frontmatter/acknowledgement.qmd
    - frontmatter/abstract.qmd
    - frontmatter/abbreviations_notation.qmd
    - chapters/intro.qmd
    - chapters/background.qmd
    - chapters/methods.qmd
    - chapters/results.qmd
    - chapters/discussion.qmd
    - references.qmd
  #appendices: 
  # - appendix/app1-paper_selection.qmd

  
  search:
    location: navbar
    type: overlay
  output-file: NMLeach_MasterThesis
  downloads:
    -  pdf


# table of content and depth of numbering set at chapter level  
toc: true
number-depth: 1

execute:
  warning: false
  massage: false



bibliography: references.bib
csl: apa7.csl

format-links: true

format:
  html:
    theme: cosmo
  pdf:
    include-in-header: 
      text: |
        \usepackage{booktabs}
        \usepackage{graphicx}
        \newcommand{\bminipage}{\begin{minipage}{0.65\textwidth}}
        \newcommand{\eminipage}{\end{minipage}}
        \newcommand{\minipagehfill}{\hfill}
        \usepackage{setspace}
        \usepackage{longtable}
        \usepackage{lscape}
        \newcommand{\blandscape}{\begin{landscape}}
        \newcommand{\elandscape}{\end{landscape}}
        \usepackage{float}
        \floatplacement{table}{H}
        \pagenumbering{gobble}
        \usepackage{titlesec}
        \titleformat{\chapter}[display]
        {\normalfont\huge\bfseries}{}{0pt}{\Huge}
        \titlespacing*{\chapter}{0pt}{-15pt}{0pt} % Adjust spacing
        
    fig-pos: 'H'
    template-partials:
      - frontmatter/before-body.tex
    documentclass: report
    classoption: ["open=any"]
    latex_engine: xelatex
    extra_dependencies: ["setspace", "geometry"]
    latex-max-runs: 3
   
    keep-tex: false
    link-citations: true
    colorlinks: false
    papersize: a4
    fontsize: 11pt
    
    linestretch: 1.5
    geometry:
      - inner=1.8cm
      - outer=1.7cm
      - top=1.9cm
      - bottom=2.5cm
      - headsep=9pt
      - headheight=11pt
      - footskip=33pt
      - ignorehead
      - ignorefoot
      - heightrounded
    



editor: visual

