# Foreword {.unnumbered .unlisted}

::: {style="text-align: justify"}
The aim of this research was to assess whether study features can explain variations in results across studies. To my knowledge, this is the first study to apply weighted meta-analysis techniques to examining the performance of machine learning models in remote sensing. While I intended to adhere to PRISMA guidelines, the exploratory nature of the topic---and my own learning journey---meant pre-registration was ultimately not conducted, and with data extraction carried out solely by myself, there is a degree of subjectivity and potential for error there. But I'm giving away spoilers for the discussion, so I'll stop myself there!

I have succeeded in building this manuscript using Quarto, with minimal stylistic adjustments after rendering. The entire code for this project is available on [GitHub](https://github.com/N-Leach/master_thesis_rs_meta-analysis), and an HTML version with integrated code chunks can be accessed on [GitHub Pages website](https://n-leach.github.io/master_thesis_rs_meta-analysis/). The data processing and paper selection analysis scripts are all available on the GitHub-hosted site under the appendix (more details about the file organisation are available on the GitHub page). I have also integrated the Leiden University master thesis cover format into the Quarto book, so if any future student would like to reuse it please do! I toyed with the idea of creating a Quarto book template but that is a project for another day.

One last thing, in the discussion of this thesis I suggest that journals should begin requesting data submissions alongside the manuscript to enable active, ongoing meta-analyses. In support of this idea, I developed a [small pilot website](https://n-leach.github.io/meta-analysis_rs/) to demonstrate how such a system might work. If anyone feels inclined to add to the dataset, there are instructions on how to do that there.

To the reader: thank you for taking the time to read my thesis--- there's still time to stop reading, and I won't know any different! If you've made it this far ---hi supervisors, and independent reader (, and mum!?)--- I would like to apologize in advance for continuing the convention of inconsistent notation across meta-analysis research. I can only hope I have been consistent within my own work as its best not to change notations $\mu$-dstream.
:::
