## Table of Notation {.unnumbered .unlisted}

The following table....

| Notation                   | Definition                                                                                                                                                                                                                                    |            Section            |
|----------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|:-----------------------------:|
| $_{rc}$                    | Index for the rows and columns of a matrix                                                                                                                                                                                                    | @sec-background, @sec-methods |
| $m_{rc}$                   | Confusion martix: the number of instances where the actual class is $r$ and the predicted class is $c$. Where $r$, is the row index, representing the actual class (reference) and $c$ is the column index, representing the predicted class. |        @sec-background        |
| $m$                        | The total number of instances in primary study's dataset (sum of all cells).                                                                                                                                                                  |               "               |
| $s$                        | Correctly classified instances                                                                                                                                                                                                                |               "               |
| $n$                        | Total number of primary studies used in this study. In @fig-prisma $n$ is the number of studies in each section.                                                                                                                              |         @sec-methods          |
| $j$                        | The study index: $j= 1,...,n$                                                                                                                                                                                                                 |               "               |
| $k_j$                      | total number of effect sizes in the $j-$th study                                                                                                                                                                                              |               "               |
| $i$                        | The effect size index within a study. If a study reports two outcomes $i: \{1, 2\}$. $i = 1, ..., k_j$                                                                                                                                        |               "               |
| $m_{ij}, s_{ij}$           | The total number of instances (the sample size) and correctly predicted class for each effect size with in each study                                                                                                                         |               "               |
| $k$                        | Total number of effect sizes gathered.                                                                                                                                                                                                        |               "               |
| $\theta, \hat{\theta}$     | True and observed effect size (overall accuracy)                                                                                                                                                                                              |               "               |
| $\kappa_j$                 | Study average effect size.                                                                                                                                                                                                                    |               "               |
| $\mu$                      | Summary (population) effect size                                                                                                                                                                                                              |               "               |
| $\sigma^2_{\text{level2}}$ | Within-study heterogeneity                                                                                                                                                                                                                    |               "               |
| $\sigma^2_{\text{level3}}$ | Between-study heterogeneity                                                                                                                                                                                                                   |               "               |
